- hosts: db_servers
  tasks:
  - name: Add MySQL repo
    yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm state=present
  - name: Install MySQL
    yum: name={{ item }} update_cache=yes state=installed
    with_items:
      - mysql
      - mysql-server
  - name: Enable Epel
    yum:
      name: epel-release
      state: latest
  - name: Install Python-devel
    yum:
      name: python-devel
      state: latest
  - name: Install Mysql-devel
    yum:
      name: mysql-devel
      state: latest
  - name: Install gcc
    yum:
      name: gcc
      state: latest
  - name: Install pip
    yum:
      name: python-pip
      state: latest
  - name: Ensure mysql started
    service:
      name: mysqld
      state: started
      enabled: yes
  - name: Install the Python MySQLB module
    pip: name=MySQL-python
  - name: Find temporary password for MySQL
    shell: "echo `grep 'temporary.*root@localhost' /var/log/mysqld.log | sed 's/.*root@localhost: //'`"
    register: mysql_root_password_temp
    tags: register
  - name: Set new password from temporary password
    shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_password }}'');" --connect-expired-password -uroot -p"{{ mysql_root_password_temp.stdout }}"'
  - name: Create a new schema
    mysql_db:
    name: jenkins_eng_4_6_1
    state: present