- hosts: db_servers
  tasks:
  - name: Add MySQL repo
    yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm state=present
  - name: Install MySQL
    yum: name={{ item }} update_cache=yes state=installed
    with_items:
      - mysql
      - mysql-server
  - name: Enable Epel
    yum:
      name: epel-release
      state: latest
  - name: Install Python-devel
    yum:
      name: python-devel
      state: latest
  - name: Install Mysql-devel
    yum:
      name: mysql-devel
      state: latest
  - name: Install gcc
    yum:
      name: gcc
      state: latest
  - name: Install pip
    yum:
      name: python-pip
      state: latest
  - name: Ensure mysql started
    service:
      name: mysqld
      state: started
      enabled: yes
  - name: Install the Python MySQLB module
    pip: name=MySQL-python
  - name: reset mysql 5.6+ default password (no longer empty)
    shell: mysql_secret=$(sudo grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}') && root -u  --password=${mysql_secret} kmsadmin123 
 