- hosts: db_servers
  tasks:
  - name: Create a new schema
    mysql_db:
      login_user: root
      login_password: '{{ mysql_root_password }}'
      name: jenkins_eng_4_6_1
      state: present